name: CreateAdmin
main: CreateAdmin.CreateAdmin
version: "1.0.4"
api:
  - 1.0.0
load: POSTWORLD
authors: ["若水", "LT_Name"]

commands:
  创造管理:
    usage: /创造管理 help
    description: "CreateAdmin 命令"
    permission: CreateAdmin.a
    aliases:
      - CreateAdmin

permissions:
  CreateAdmin.a:
    default: op